---
- name:               IIMS EAP Deployment 
  hosts:              localhost
  gather_facts:       no
      
  tasks:
  - include_vars:
      file:           "{{ playbook_dir + '/varfiles/iims_all.yml' }}"

  - include_role:
      name:           status_app
    when:             >
                      action == 'stop'      or
                      deploy == 'deploy'    or
                      action == 'start'     or
                      action == 'status'

  - include_role:
    name:           stop_app 
    when:             >
                      action == 'stop'      or
                      deploy == 'deploy'
  
  - include_role:
      name:           deploy_app
    when:             >
                      deploy == 'deploy'

  - include_role:
      name:           start_app
    when:             >
                      action == 'start'     or
                      deploy == 'deploy'  

  

