---
  - name: Import Node Name Verification task
    import_tasks: validate_node_name.yml

  - name: Import Data Aggregate Verification task
    import_tasks: validate_data_aggr.yml

  - name: Import Data Aggregate Verification task
    import_tasks: validate_data_aggr_snap.yml
