# 
- name                : Create list of unique node model
  set_fact            :
     uniq_node_model  : "{{ uniq_node_model |default([]) + [ { 'model' : model} ] }}"
  with_items          : "{{ ontap_facts.system_node_info }}"
  vars                :
    model             : "{{ ontap_facts.system_node_info[item].node_model }}"

- name: Check if var_platform_[node_model].yml exists
  stat:
     path: "{{ varfiles_dir + '/var_platform_' + item.model + '.yml' }}"
  register: stat_result
  with_items: "{{ uniq_node_model | unique }}"
- set_fact:
    model: "{{ item.model }}"
  with_items: "{{ uniq_node_model | unique }}"
- set_fact:
    clucheck: "{{ hostname }}"
  when: model != 'SIMBOX'
- set_fact:
    clucheck: "cDOT96"
  when: model == 'SIMBOX'
- fail:
    msg: "var file for ontap model {{ uniq_node_model | unique }} not found !"
  when:
    - stat_result.results[0].stat.exists == false
- name: Load node model specific var files
  include_vars:
    file: "{{ item.invocation.module_args.path }}"
  with_items: "{{ stat_result.results }}"
  loop_control:
    label: "{{ item.invocation.module_args.path }}"
  when: item.stat.exists
- name: Check if var_[cluster].yml exists
  stat:
     path: "{{ clustervarfile }}"
  register: cluvarstat_result
- fail:
   msg: "File {{ clustervarfile }} not found !   Has the file been generated by the pb_new_cluster_deployement.yml playbook ?   Validate your input and relaunch the playbook"
  when: cluvarstat_result.stat.exists == false
- name: Load cluster specific var files
  include_vars:
    file: "{{ clustervarfile }}"
  when: cluvarstat_result.stat.exists